title: ""
description: "H S Helson Go's research and notes"
url: "https://hs293go.github.io"
baseurl: ""

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

minimal_mistakes_skin: dark

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: null

author:
  name: "H S Helson Go"
  avatar: "/assets/images/avatar.jpg"
  bio: "PhD in Robotics â€” Engineering, control, and autonomy."
  location: "Canada"
  github: hs293go

include:
  - _pages

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: single
      toc: true
      toc_sticky: true
      math: true
      sidebar:
        nav: "main"
      classes: wide

permalink: /:categories/:title/
